
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_outputlabel(object):
    def setupUi(self, outputlabel):
        outputlabel.setObjectName("outputlabel")
        outputlabel.resize(400, 498)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        outputlabel.setFont(font)
        self.centralwidget = QtWidgets.QWidget(outputlabel)
        self.centralwidget.setObjectName("centralwidget")
        self.outputlabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.outputlabel_2.setGeometry(QtCore.QRect(10, 10, 380, 80))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.outputlabel_2.setFont(font)
        self.outputlabel_2.setFrameShape(QtWidgets.QFrame.Box)
        self.outputlabel_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.outputlabel_2.setLineWidth(4)
        self.outputlabel_2.setMidLineWidth(12)
        self.outputlabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputlabel_2.setObjectName("outputlabel_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 170, 381, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(4, 4, 4, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.seven = QtWidgets.QPushButton(self.layoutWidget , clicked = lambda : self.press_it("7"))
        self.seven.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.seven.setFont(font)
        self.seven.setAutoDefault(False)
        self.seven.setDefault(False)
        self.seven.setFlat(False)
        self.seven.setObjectName("seven")
        self.horizontalLayout_2.addWidget(self.seven)
        self.eight = QtWidgets.QPushButton(self.layoutWidget , clicked = lambda : self.press_it("8"))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.eight.setFont(font)
        self.eight.setAutoDefault(False)
        self.eight.setDefault(False)
        self.eight.setFlat(False)
        self.eight.setObjectName("eight")
        self.horizontalLayout_2.addWidget(self.eight)
        self.nine = QtWidgets.QPushButton(self.layoutWidget , clicked = lambda : self.press_it("9"))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.nine.setFont(font)
        self.nine.setAutoDefault(False)
        self.nine.setDefault(False)
        self.nine.setFlat(False)
        self.nine.setObjectName("nine")
        self.horizontalLayout_2.addWidget(self.nine)
        self.mul = QtWidgets.QPushButton(self.layoutWidget , clicked = lambda : self.press_it("x"))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.mul.setFont(font)
        self.mul.setAutoDefault(False)
        self.mul.setDefault(False)
        self.mul.setFlat(False)
        self.mul.setObjectName("mul")
        self.horizontalLayout_2.addWidget(self.mul)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 240, 381, 61))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(4, 4, 4, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.four = QtWidgets.QPushButton(self.layoutWidget_2 , clicked = lambda : self.press_it("4"))
        self.four.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.four.setFont(font)
        self.four.setAutoDefault(False)
        self.four.setDefault(False)
        self.four.setFlat(False)
        self.four.setObjectName("four")
        self.horizontalLayout_3.addWidget(self.four)
        self.five = QtWidgets.QPushButton(self.layoutWidget_2 , clicked = lambda : self.press_it("5"))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.five.setFont(font)
        self.five.setAutoDefault(False)
        self.five.setDefault(False)
        self.five.setFlat(False)
        self.five.setObjectName("five")
        self.horizontalLayout_3.addWidget(self.five)
        self.six = QtWidgets.QPushButton(self.layoutWidget_2 , clicked = lambda : self.press_it("6"))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.six.setFont(font)
        self.six.setAutoDefault(False)
        self.six.setDefault(False)
        self.six.setFlat(False)
        self.six.setObjectName("six")
        self.horizontalLayout_3.addWidget(self.six)
        self.min = QtWidgets.QPushButton(self.layoutWidget_2 , clicked = lambda : self.press_it("-"))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.min.setFont(font)
        self.min.setAutoDefault(False)
        self.min.setDefault(False)
        self.min.setFlat(False)
        self.min.setObjectName("min")
        self.horizontalLayout_3.addWidget(self.min)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 310, 381, 61))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(4, 4, 4, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.one = QtWidgets.QPushButton(self.layoutWidget_3 , clicked = lambda : self.press_it("1"))
        self.one.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.one.setFont(font)
        self.one.setAutoDefault(False)
        self.one.setDefault(False)
        self.one.setFlat(False)
        self.one.setObjectName("one")
        self.horizontalLayout_4.addWidget(self.one)
        self.two = QtWidgets.QPushButton(self.layoutWidget_3 , clicked = lambda : self.press_it("2"))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.two.setFont(font)
        self.two.setAutoDefault(False)
        self.two.setDefault(False)
        self.two.setFlat(False)
        self.two.setObjectName("two")
        self.horizontalLayout_4.addWidget(self.two)
        self.three = QtWidgets.QPushButton(self.layoutWidget_3 , clicked = lambda : self.press_it("3"))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.three.setFont(font)
        self.three.setAutoDefault(False)
        self.three.setDefault(False)
        self.three.setFlat(False)
        self.three.setObjectName("three")
        self.horizontalLayout_4.addWidget(self.three)
        self.plus = QtWidgets.QPushButton(self.layoutWidget_3 , clicked = lambda : self.press_it("+"))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.plus.setFont(font)
        self.plus.setAutoDefault(False)
        self.plus.setDefault(False)
        self.plus.setFlat(False)
        self.plus.setObjectName("plus")
        self.horizontalLayout_4.addWidget(self.plus)
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 380, 381, 61))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(4, 4, 4, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.unknown = QtWidgets.QPushButton(self.layoutWidget_4)
        self.unknown.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.unknown.setFont(font)
        self.unknown.setAutoDefault(False)
        self.unknown.setDefault(False)
        self.unknown.setFlat(False)
        self.unknown.setObjectName("unknown")
        self.horizontalLayout_5.addWidget(self.unknown)
        self.zero = QtWidgets.QPushButton(self.layoutWidget_4 , clicked = lambda : self.press_it("0"))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.zero.setFont(font)
        self.zero.setAutoDefault(False)
        self.zero.setDefault(False)
        self.zero.setFlat(False)
        self.zero.setObjectName("zero")
        self.horizontalLayout_5.addWidget(self.zero)
        self.dot = QtWidgets.QPushButton(self.layoutWidget_4 , clicked = lambda : self.press_it("."))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.dot.setFont(font)
        self.dot.setAutoDefault(False)
        self.dot.setDefault(False)
        self.dot.setFlat(False)
        self.dot.setObjectName("dot")
        self.horizontalLayout_5.addWidget(self.dot)
        self.equ = QtWidgets.QPushButton(self.layoutWidget_4 , clicked = lambda : self.press_it("="))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.equ.setFont(font)
        self.equ.setAutoDefault(False)
        self.equ.setDefault(False)
        self.equ.setFlat(False)
        self.equ.setObjectName("equ")
        self.horizontalLayout_5.addWidget(self.equ)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 100, 381, 61))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.percent = QtWidgets.QPushButton(self.layoutWidget1 , clicked = lambda : self.press_it("%"))
        self.percent.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.percent.setFont(font)
        self.percent.setAutoDefault(False)
        self.percent.setDefault(False)
        self.percent.setFlat(False)
        self.percent.setObjectName("percent")
        self.horizontalLayout.addWidget(self.percent)
        self.c = QtWidgets.QPushButton(self.layoutWidget1 , clicked = lambda : self.clear())
        font = QtGui.QFont()
        font.setPointSize(21)
        self.c.setFont(font)
        self.c.setAutoDefault(False)
        self.c.setDefault(False)
        self.c.setFlat(False)
        self.c.setObjectName("c")
        self.horizontalLayout.addWidget(self.c)
        self.delt = QtWidgets.QPushButton(self.layoutWidget1 , clicked = lambda : self.delete())
        font = QtGui.QFont()
        font.setPointSize(21)
        self.delt.setFont(font)
        self.delt.setAutoDefault(False)
        self.delt.setDefault(False)
        self.delt.setFlat(False)
        self.delt.setObjectName("delt")
        self.horizontalLayout.addWidget(self.delt)
        self.dev = QtWidgets.QPushButton(self.layoutWidget1 , clicked = lambda : self.press_it("/"))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.dev.setFont(font)
        self.dev.setAutoDefault(False)
        self.dev.setDefault(False)
        self.dev.setFlat(False)
        self.dev.setObjectName("dev")
        self.horizontalLayout.addWidget(self.dev)
        outputlabel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(outputlabel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        outputlabel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(outputlabel)
        self.statusbar.setObjectName("statusbar")
        outputlabel.setStatusBar(self.statusbar)

        self.retranslateUi(outputlabel)
        QtCore.QMetaObject.connectSlotsByName(outputlabel)

    def press_it(self,text):
        self.outputlabel_2.setText( self.outputlabel_2.text() + text)

    def clear(self):
        self.outputlabel_2.setText("0")

    def delete(self):
        self.outputlabel_2.setText(self.outputlabel_2.text()[:-1])

    def retranslateUi(self, outputlabel):
        _translate = QtCore.QCoreApplication.translate
        outputlabel.setWindowTitle(_translate("outputlabel", "calculator"))
        self.outputlabel_2.setText(_translate("outputlabel", "0"))
        self.seven.setText(_translate("outputlabel", "7"))
        self.eight.setText(_translate("outputlabel", "8"))
        self.nine.setText(_translate("outputlabel", "9"))
        self.mul.setText(_translate("outputlabel", "x"))
        self.four.setText(_translate("outputlabel", "4"))
        self.five.setText(_translate("outputlabel", "5"))
        self.six.setText(_translate("outputlabel", "6"))
        self.min.setText(_translate("outputlabel", "-"))
        self.one.setText(_translate("outputlabel", "1"))
        self.two.setText(_translate("outputlabel", "2"))
        self.three.setText(_translate("outputlabel", "3"))
        self.plus.setText(_translate("outputlabel", "+"))
        self.unknown.setText(_translate("outputlabel", "+/-"))
        self.zero.setText(_translate("outputlabel", "0"))
        self.dot.setText(_translate("outputlabel", "."))
        self.equ.setText(_translate("outputlabel", "="))
        self.percent.setText(_translate("outputlabel", "%"))
        self.c.setText(_translate("outputlabel", "c"))
        self.delt.setText(_translate("outputlabel", "<<"))
        self.dev.setText(_translate("outputlabel", "/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    outputlabel = QtWidgets.QMainWindow()
    ui = Ui_outputlabel()
    ui.setupUi(outputlabel)
    outputlabel.show()
    sys.exit(app.exec_())

